In [2]:
import pandas as pd

path = "../data/raw/Mobile_Parts_Wholesale_Dataset.xlsx"
sales = pd.read_excel(path, sheet_name="Sales_Transactions")
sales['order_date'] = pd.to_datetime(sales['order_date'])

print(sales.shape)
sales.head()

(6016, 9)

,order_id,customer_id,product_id,order_date,quantity,unit_price_inr,discount_pct,total_amount_inr,payment_mode
0,O000001,C0095,P0103,2025-01-22,8,250,5,1900.0,Bank Transfer
1,O000002,C0095,P0048,2025-01-22,8,410,5,3116.0,Bank Transfer
2,O000003,C0009,P0018,2025-01-29,4,1070,0,4280.0,Bank Transfer
3,O000004,C0009,P0040,2025-01-29,8,2890,0,23120.0,Bank Transfer
4,O000005,C0009,P0114,2025-01-29,2,380,10,684.0,UPI

In [3]:
daily_demand = sales.groupby('order_date').agg(
    total_qty=('quantity', 'sum'),
    total_revenue=('total_amount_inr', 'sum')
).reset_index()

print(daily_demand.shape)
daily_demand.head()

(488, 3)

  order_date  total_qty  total_revenue
0 2025-01-22         16         5016.0
1 2025-01-29         21        31167.0
2 2025-01-31         18        48064.0
3 2025-02-01         28        34302.5
4 2025-02-02         30        16223.0

In [4]:
full_range = pd.date_range(start=daily_demand['order_date'].min(),
                            end=daily_demand['order_date'].max(), freq='D')
daily_demand = daily_demand.set_index('order_date').reindex(full_range, fill_value=0).reset_index()
daily_demand = daily_demand.rename(columns={'index': 'order_date'})

print(daily_demand.shape)
daily_demand.head()

(524, 3)

  order_date  total_qty  total_revenue
0 2025-01-22         16         5016.0
1 2025-01-23          0            0.0
2 2025-01-24          0            0.0
3 2025-01-25          0            0.0
4 2025-01-26          0            0.0

In [5]:
daily_demand.to_csv("../data/processed/daily_demand.csv", index=False)
print("Saved daily_demand.csv")

Saved daily_demand.csv